### ISSUE TITLE
[bug]: When using Proxy, cannot see funded wallet details

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/jam-wrapper#3]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

13.0.1

### Browser

Firefox

### Browser Version

104.1

### Current Behavior

after funding a wallet, a 502 error is showing when trying to access wallet details

### Expected Behavior

Wallet details should show without error

### Steps to Reproduce

1. install JAM
2. create wallet
3. fund wallet
4. view wallet

**Comment by LambdaDev22** [comment]
The issue is when using Bitcoin Proxy Server, using core as the only dependency fixes this. 

<img width="808" alt="Screenshot 2022-12-18 at 4 30 38 PM" src="https://user-images.githubusercontent.com/112665215/208322749-c6988e95-5c5f-4185-9858-2105a8924d00.png">

**Comment by LambdaDev22** [comment]
Issue is when using Bitcoin Proxy as a dependency, changing it bitcoin core fixes this. 

<img width="808" alt="Screenshot 2022-12-18 at 4 30 38 PM" src="https://user-images.githubusercontent.com/112665215/208323365-700fd7b4-c9fa-4cde-8db7-b5381505d742.png">

**Comment by islandbitcoin** [comment]
Removed Proxy as an option.
